export const cssProperties = {
  backgroundColor: 'backgroundColor',
  backgroundImage: 'backgroundImage',
  backgroundSize: 'backgroundSize',
  backgroundPosition: 'backgroundPosition',
  backgroundRepeat: 'backgroundRepeat',
  backgroundAttachment: 'backgroundAttachment',
  color: 'color',
  fill: 'fill',
  stroke: 'stroke',
  boxShadow: 'boxShadow',
  mixBlendMode: 'mixBlendMode',
  backgroundBlendMode: 'backgroundBlendMode',
  opacity: 'opacity',
  alignItems: 'alignItems',
  alignContent: 'alignContent',
  justifyItems: 'justifyItems',
  justifyContent: 'justifyContent',
  flexWrap: 'flexWrap',
  flexDirection: 'flexDirection',
  flexFlow: 'flexFlow',
  flexGrow: 'flexGrow',
  flexShrink: 'flexShrink',
  flexBasis: 'flexBasis',
  justifySelf: 'justifySelf',
  alignSelf: 'alignSelf',
  order: 'order',
  placeItems: 'placeItems',
  placeContent: 'placeContent',
  placeSelf: 'placeSelf',
  rowGap: 'rowGap',
  columnGap: 'columnGap',
  appearance: 'appearance',
  cursor: 'cursor',
  resize: 'resize',
  userSelect: 'userSelect',
  pointerEvents: 'pointerEvents',
  outlineOffset: 'outlineOffset',
  outlineColor: 'outlineColor',
  outlineStyle: 'outlineStyle',
  outlineWidth: 'outlineWidth',
  width: 'width',
  height: 'height',
  minWidth: 'minWidth',
  minHeight: 'minHeight',
  maxWidth: 'maxWidth',
  maxHeight: 'maxHeight',
  overflowX: 'overflowX',
  overflowY: 'overflowY',
  overscrollBehaviorX: 'overscrollBehaviorX',
  overscrollBehaviorY: 'overscrollBehaviorY',
  display: 'display',
  verticalAlign: 'verticalAlign',
  boxSizing: 'boxSizing',
  boxDecorationBreak: 'boxDecorationBreak',
  float: 'float',
  objectFit: 'objectFit',
  objectPosition: 'objectPosition',
  visibility: 'visibility',
  isolation: 'isolation',
  listStyleType: 'listStyleType',
  listStylePosition: 'listStylePosition',
  listStyleImage: 'listStyleImage',
  position: 'position',
  top: 'top',
  bottom: 'bottom',
  left: 'left',
  right: 'right',
  zIndex: 'zIndex',
  margin: 'margin',
  marginTop: 'marginTop',
  marginRight: 'marginRight',
  marginBottom: 'marginBottom',
  marginLeft: 'marginLeft',
  padding: 'padding',
  paddingTop: 'paddingTop',
  paddingRight: 'paddingRight',
  paddingBottom: 'paddingBottom',
  paddingLeft: 'paddingLeft',
}

export const cssPseudoProperties = {
  _hover: '&:hover, &[data-hover]',
  _active: '&:active, &[data-active]',
  _focus: ' &:focus, &[data-focus]',
  _disabled: '&[disabled], &[aria-disabled=true], &[data-disabled]',
  _readOnly: '&[aria-readonly=true], &[readonly], &[data-readonly]',
  _before: '&::before',
  _after: '&::after',
  _checked: '&[aria-checked=true], &[data-checked]',
  _invalid: '&[aria-invalid=true], &[data-invalid]',
  _valid: '&[data-valid], &[data-state=valid]',
  _hidden: '&[hidden], &[data-hidden]',
  _visited: '&:visited',
  _indeterminate: '&:indeterminate, &[aria-checked=mixed], &[data-indeterminate]',
}

export const allCssProperties = { ...cssProperties, ...cssPseudoProperties }
